#!/usr/bin/env bash
# build.sh — generates all shell plugin files from reasons.txt
# Usage: ./build.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REASONS_FILE="$SCRIPT_DIR/reasons.txt"

if [[ ! -f "$REASONS_FILE" ]]; then
  echo "Error: reasons.txt not found at $REASONS_FILE" >&2
  exit 1
fi

# Read reasons into an array, skipping blank lines and comments
# (while read loop used for bash 3.2 compat — macOS default)
REASONS=()
while IFS= read -r line; do
  REASONS+=("$line")
done < <(grep -v '^\s*$\|^\s*#' "$REASONS_FILE")
COUNT=${#REASONS[@]}
echo "Building from $COUNT reasons..."

# ---------------------------------------------------------------------------
# Helper: capitalize first letter of a string (bash 4+)
# ---------------------------------------------------------------------------
capitalize() { echo "${1^}"; }

# ---------------------------------------------------------------------------
# FISH
# ---------------------------------------------------------------------------
FISH_OUT="$SCRIPT_DIR/conf.d/enjoy_life.fish"
mkdir -p "$SCRIPT_DIR/conf.d"

{
  echo "# enjoy_life.fish — auto-generated by build.sh, do not edit directly"
  echo "# Edit reasons.txt and run ./build.sh to regenerate"
  echo ""
  echo "set -l reasons \\"
  for i in "${!REASONS[@]}"; do
    reason="${REASONS[$i]}"
    # Capitalize first letter at build time — avoids runtime Fish version differences
    reason="${reason^}"
    if [[ $i -lt $(( COUNT - 1 )) ]]; then
      echo "    \"$reason\" \\"
    else
      echo "    \"$reason\""
    fi
  done
  echo ""
  echo "set_color cyan"
  echo "echo \"💙 \$reasons[(random 1 (count \$reasons))]\""
  echo "set_color normal"
} > "$FISH_OUT"
echo "✓ $FISH_OUT"

# ---------------------------------------------------------------------------
# ZSH
# ---------------------------------------------------------------------------
ZSH_OUT="$SCRIPT_DIR/enjoy-life.plugin.zsh"

{
  echo "# enjoy-life.plugin.zsh — auto-generated by build.sh, do not edit directly"
  echo "# Edit reasons.txt and run ./build.sh to regenerate"
  echo ""
  echo "local reasons=("
  for reason in "${REASONS[@]}"; do
    echo "  \"$reason\""
  done
  echo ")"
  echo ""
  echo "local idx=\$(( RANDOM % \${#reasons[@]} + 1 ))"
  echo "local reason=\"\${reasons[\$idx]}\""
  echo "reason=\"\${(U)reason:0:1}\${reason:1}\""
  echo ""
  echo "echo \"\\\033[0;36m💙 \${reason}\\\033[0m\""
} > "$ZSH_OUT"
echo "✓ $ZSH_OUT"

# ---------------------------------------------------------------------------
# BASH
# ---------------------------------------------------------------------------
BASH_OUT="$SCRIPT_DIR/enjoy-life.bash"

{
  echo "# enjoy-life.bash — auto-generated by build.sh, do not edit directly"
  echo "# Edit reasons.txt and run ./build.sh to regenerate"
  echo ""
  echo "_enjoy_life() {"
  echo "  local reasons=("
  for reason in "${REASONS[@]}"; do
    echo "    \"$reason\""
  done
  echo "  )"
  echo ""
  echo "  local count=\${#reasons[@]}"
  echo "  local idx=\$(( RANDOM % count ))"
  echo "  local reason=\"\${reasons[\$idx]}\""
  echo "  reason=\"\${reason^}\""
  echo ""
  echo "  echo -e \"\\\033[0;36m💙 \${reason}\\\033[0m\""
  echo "}"
  echo ""
  echo "_enjoy_life"
} > "$BASH_OUT"
echo "✓ $BASH_OUT"

# ---------------------------------------------------------------------------
# POWERSHELL
# ---------------------------------------------------------------------------
PS_OUT="$SCRIPT_DIR/enjoy-life.ps1"

{
  echo "# enjoy-life.ps1 — auto-generated by build.sh, do not edit directly"
  echo "# Edit reasons.txt and run ./build.sh to regenerate"
  echo ""
  echo "\$reasons = @("
  for i in "${!REASONS[@]}"; do
    reason="${REASONS[$i]}"
    if [[ $i -lt $(( COUNT - 1 )) ]]; then
      echo "    \"$reason\""
    else
      echo "    \"$reason\""
    fi
  done
  echo ")"
  echo ""
  echo "\$reason = \$reasons | Get-Random"
  echo "\$reason = \$reason.Substring(0,1).ToUpper() + \$reason.Substring(1)"
  echo ""
  echo "Write-Host \"💙 \$reason\" -ForegroundColor Cyan"
} > "$PS_OUT"
echo "✓ $PS_OUT"

echo ""
echo "Done — all 4 shell files regenerated from $COUNT reasons."